#!/usr/bin/python

import os
import sys
import string


x=sys.argv[1:]

for i in x:
	s=''.join(i)
	if '/' in s:
		l=s.rsplit('/',1)[0]
		d=s.rsplit('/',1)[1]

		if os.path.isdir(s) :
    			print "makedir: cannot create directory '" + d  + "': File exists"

		if not os.path.isdir(s):
   			os.makedirs(s)

	else:
		pwd=os.getcwd()
		st=''.join(i)
		os.mkdir(pwd + "/" + st,0755)
		


